### System configuration
ts: 0.2   # Size of the time-step (sampling time)

### Scanner specifications
angle_min: -1.5708 # -90 degrees
angle_max: 1.5708 # 90 degrees
angle_increment: 0.174533 # 1 degree = 0.0174533 radians
range_min: 0.1
range_max: 10.0
frame_id: "sparse_laser"